### ISSUE TITLE
Cannot import functions "is", "check", "createMatch"

### ISSUE THREAD

**Issue by Pi77Bull** [GoogleFeud/ts-runtime-checks#33]
**Describe the bug**
The imported functions "is", "check", "createMatch" are undefined

**Playground link**
https://stackblitz.com/edit/node-xw59bs?file=src%2Fapp%2Fapp.component.ts

**Expected behavior**
Functions should not be undefined.

**Additional context**
I'm trying to use this tool in an Angular application and the types are working fine, only the functions don't work.

Also, the application first didn't compile because the type ts.TypeMapper in genValidator.d.ts did not exist. I had to add a // @ts-ignore to make it work.

Do you know by any chance what could be wrong?

Also, thank you very much for your work! You've done an amazing job.

**Comment by Pi77Bull** [comment]
Ok, nevermind. The types are not working either. I must be doing something very wrong.

**Comment by GoogleFeud** [comment]
Hi! If you're getting type errors coming from the library you can set the `skipLibCheck` setting in the typescript config file to `true`, or you can install the `@types/ts-expose-internals` npm package as a dev dependency. 

As for webpack, currently, we use the `path` module for the JSON schema feature, so you'll have to provide a polyfill to webpack for that:
```ts
  config.resolve.fallback = { 
    path: false
  }
```
(I'm gonna make it so `path` doesn't get imported if the option is set to false, so you won't need this in the future!)

It's also a good idea to only import types and define the utility functions yourself, because otherwise webpack is gonna bundle the entire lib when it's not necessary. The utility functions don't really exist, they're ambient functions, and when they get called the library replaces the calls with the validation code. The way the library detects them is with a default type parameter which includes the `__$marker` property set to the utility name:

```ts
import type { Assert, ValidationError } from 'ts-runtime-checks';

export declare function is<T, _M = { __$marker: "is" }>(prop: unknown) : prop is T;
export declare function check<T, _rawErrorData extends boolean = false, _M = { __$marker: "check" }>(prop: unknown) : [T, Array<_rawErrorData extends true ? ValidationError : string>];
export declare function createMatch<R, U = unknown, _M = { __$marker: "createMatch" }>(fns: ((val: any) => R)[], noDiscriminatedObjAssert?: boolean) : (val: U) => R;
```

**Comment by Pi77Bull** [comment]
Great. That works perfectly! And I think I can apply that solution to another problem of mine that I had for a loong time.

Thank you very much :)

Now, is there a way to use this tool with TypeScript 4? Because I'm currently using Angular 14 which is not yet using TypeScript 5. If not that's ok. I need to update to the latest version of Angular at some point anyway ^^

**Comment by GoogleFeud** [comment]
I think you should be able to as I don't think there were any breaking changes with the typescript's API, but not too sure!

**Comment by Pi77Bull** [comment]
Unfortunately while building the application, it throws the following error:

`Error: typescript_1.default.isTypeDeclaration is not a function`

Is `@types/ts-expose-internals` supposed to fix that?

**Comment by GoogleFeud** [comment]
Sorry for the late reply, it seems like the transformer doesn't work with typescript 4.0
